### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by JasCodes** [leonardoInf/cli_dialog#1]
Tested in powershell, arrow keys won't work...

**Comment by leonardoInf** [comment]
Hello @jascodes 
thanks for commenting. I am aware of the issue and it is mentioned in the Readme (https://github.com/leonardoInf/cli_dialog#windows). Maybe I will try to fix the issue but I have a lot to do this week.

**Comment by JasCodes** [comment]
No problem, just wanted to convey it.

Thx

**Comment by leonardoInf** [comment]
This package looks promising for capturing arrow keys on Windows: https://pub.dev/packages/dart_console

**Comment by ShreyashSaitwal** [comment]
@leonardoInf Any update on this issue?

**Comment by leonardoInf** [comment]
Fixed with 0.4.0. Thank you for your interest in this package.
